### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by nrayburn-tech** [fastify/accept-negotiator#26]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm looking to update this repo for v5. https://github.com/fastify/fastify/issues/5116

Changes Needed (Please let me know if anything might be missing)
- Pin tap to 16.3.9
- Update workflows to use v4 (temporarily pointing directly to a git sha)
- ~Update `engines` in package.json to >= 18~ Remove engines from package.json
- Update dependabot config to ignore major tap versions

**Comment by metcoder95** [comment]
If it weren't because the warning log gets missed quite easily when installing, I'd say it provides good feedback to the user. But as it is not forced, and anyway `fp` enforces already specific versions of `fastify`; that should be enough. So +1 on drop it

**Comment by nrayburn-tech** [comment]
Updated the PR, but I think I'm going to leave it as a draft until the workflow v4 tag is available unless there's a reason to merge it in sooner.  (Going to follow the same pattern for my other PRs of just leaving them as a draft too.)

**Comment by gurgunday** [comment]
I just saw the issue, sorry for taking over!

There are [many other repositories available to do an upgrade](https://github.com/fastify/fastify/issues/5116), so it would still be amazing if you could help!
